### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by collinmsn** [stvp/resp#1]
`*3\r\n*4\r\n:5462\r\n:10922\r\n*2\r\n$9\r\n127.0.0.1\r\n:7932\r\n*2\r\n$9\r\n127.0.0.1\r\n:8032\r\n*4\r\n:0\r\n:5461\r\n*2\r\n$9\r\n127.0.0.1\r\n:7931\r\n*2\r\n$9\r\n127.0.0.1\r\n:8031\r\n*3\r\n:10923\r\n:16383\r\n*2\r\n$9\r\n127.0.0.1\r\n:7933\r\n`

this is a valid RESP object but the reader failed to decode it

**Comment by tysonmote** [comment]
Fixed in https://github.com/stvp/resp/commit/611f1d8ba9079fd18ff0bde8716978129f3908b2

Thanks!
