### ISSUE TITLE
The minimum valid command is not PING, but GET.

### ISSUE THREAD

**Issue by dzrw** [stvp/resp#3]
According to http://redis.io/commands, the shortest command is `GET` and not `PING`.

https://github.com/stvp/resp/blob/master/resp.go#L14-L15

``` Go
    // The minimum valid command is "*1\r\n$3\r\nGET\r\n"
    minCommandLen = 13
```

However, I would argue that the minimum support command should simply be a single character - the only constraint in the RESP specification is the prohibition of NULL Bulk Strings.

**Comment by tysonmote** [comment]
@politician I think you're right. And because this library shouldn't be tied directly to Redis' command set, it makes sense to just follow the RESP guidelines. I changed the minimum length in c45cd29.
